### ISSUE TITLE
[BUG] recipe related 

### ISSUE THREAD

**Issue by PhanaticD** [LoneDev6/Issues-ItemsAdder#295]
paper 1.15.2
```

[08:34:49 WARN]: [ItemsAdder] Plugin ItemsAdder v2.0.26 generated an exception while executing task 17621
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_231]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_231]
        at dev.lone.itemsadder.e.g.c.c.a(SourceFile:88) ~[?:?]
        at dev.lone.itemsadder.e.g.c.c.b(SourceFile:110) ~[?:?]
        at dev.lone.itemsadder.h.c.a(SourceFile:71) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

```

**Comment by LoneDev6** [comment]
Continue here: https://github.com/LoneDev6/Issues-ItemsAdder/issues/260#issuecomment-652925500
