### ISSUE TITLE
[BUG] idk

### ISSUE THREAD

**Issue by PhanaticD** [LoneDev6/Issues-ItemsAdder#296]
```
[17:46:50] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ItemsAdder v2.0.26
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_231]
        at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_231]
        at dev.lone.itemsadder.h.c.a(SourceFile:136) ~[?:?]
        at dev.lone.itemsadder.h.b.b(SourceFile:144) ~[?:?]
        at dev.lone.itemsadder.Libs.fr.mrmicky.fastinv.FastInv.p(SourceFile:316) ~[?:?]
        at dev.lone.itemsadder.Libs.fr.mrmicky.fastinv.FastInvManager$1.onInventoryClick(SourceFile:50) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2375) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1224) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-"9fa6ba267"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

```

**Comment by LoneDev6** [comment]
duplicate https://github.com/LoneDev6/Issues-ItemsAdder/issues/260
